apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-messaging-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging
  template:
    metadata:
      labels:
        app: messaging
    spec:
    containers:
      - name: django-container
        image: your-dockerhub-username/django-messaging-app:latest
        ports:
        - containerPort: 8000
    env:
        - name: DJANGO_SETTINGS_MODULE
        - value: messaging_app.settings  # Adjust to your settings module
        - name: PYTHONUNBUFFERED
        - value: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: messaging-service
spec:
  type: ClusterIP
  selector:
    app: messaging
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
